---
title: "RISEUP Census Tract Level Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill 
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=250}
-----------------------------------------------------------------------

<font size="3.5">

This map displays census tract-level data in Hamilton County .

Using the menu on the left-hand side of the map, you can toggle variables on/off.

Clicking on a census tract displays all variables for that census tract

</font>

<font size="3">

Variables Include: 

  * [Community Material Depreivaiton Index](https://geomarker.io/dep_inde)

  * Neighborhood Atlas Area Deprivation Index
      
  * American Community Survey Sociodeomgraphic Variables
      + Fraction Assisted Income
      + Fraction High School Education
      + Median Income
      + Fraction No Health Insurance
      + Fraction Poverty
      + Fraction Vacant Housing
  
  * National Walkability Index
  
  * Nancy Krieger's Index of Concentrated Extremes (ICE)
  
  * EPA EJScreen
      + Lead Paint Indicator
      + Concentration of Diesel Particulate Matter in Air (ug/m3)
      + Air Toxics Respiratory Hazard Index
      + Traffic Proximity and Volume
      + Ozone Seasonal Average of Daily Maximum 8-Hour Concentration (ppb)
      + Annual Average PM2.5 Level in Air (ug/m3)
      
  * Child Opportunity Index
      + Overall
      + Education Domain
      + Health and Environment Domain
      + Social and Economic Domain
      
  * Census' Community Resilience Index
      + Rate of Individuals with One or Two Risk Factors
      + Rate of Individuals with Three or More Risk Factors
      
  * Mental Health Professional Shortage Areas
  
  * Primary Care Professional Shortage Areas
  
  * Medically Underserved Areas
  
</font>

<br>

<br>

<br>

<font size="2">

Map created by CCHMC GRAPPH.

For questions, contact Cole.Brokamp@cchmc.org

</font>

Column {data-width=750}
-----------------------------------------------------------------------

```{r data}
library(tidyverse)
library(tmap)
library(leaflet)


census_mega_data <- readRDS("census_mega_dataset-main/census_mega_data_0.2.rds")
tract_hpsa_pc <- readRDS("data/hpsa_pc.rds")
mua <- readRDS("data/mua.rds") %>% 
  rename(census_tract_id = census_tract_fips)
d.h <- readRDS("data/hamilton_data.rds")

d <- census_mega_data %>% 
  filter(census_tract_vintage == 2010) %>% 
  select(census_tract_id, census_tract_vintage,
         dep_index, fraction_assisted_income, fraction_high_school_edu, median_income,       
         fraction_no_health_ins, fraction_poverty, fraction_vacant_housing,
         adi,
         walkability_index,
         ice,
         lead_paint, diesel_pm, resp_hazard_ind, traffic_proximity, ozone_conc, pm_conc,
         coi, coi_education, coi_health_env, coi_social_econ,
         pct_1or2_risk_factors, pct_3ormore_risk_factors,
         hpsa_mh = hpsa,
         ) %>% 
  left_join(., tract_hpsa_pc, by='census_tract_id') %>%  # primary care professional shortage areas
  left_join(., mua, by='census_tract_id') %>%     # medically underserved areas
  mutate(hpsa_mh = replace(hpsa_mh,
                           is.na(hpsa_mh),
                           'no'),
         hpsa_pc = replace(hpsa_pc,
                           is.na(hpsa_pc),
                           'no'),
         mua = ifelse(mua == 0 | is.na(mua),
                      'no',
                      'yes')
         )

```

```{r map, fig.width = 13.5, fig.height = 10, fig.align='center'}

tmap_mode('view')
tmap_options(max.categories = 81)


legend_labels <-  c('Community Material Deprivation Index' = 'dep_index', #1
                    'Neighborhood Atlas Area Deprivation Index' = 'adi', #2
                    'Index of Concentration at the Extremes' = 'ice', #3
                    '% Poverty' = 'fraction_poverty', #4
                    '% Assisted Income' = 'fraction_assisted_income', #5
                    '% No Health Insurance' = 'fraction_no_health_ins', #6
                    '% Vacant Housing' = 'fraction_vacant_housing', #7
                    'EPA EJScreen - Lead Paint Indicator' = 'lead_paint', #8
                    'EPA EJScreen - Concentration of Diesel Particulate Matter in Air (ug/m3)' = 'diesel_pm', #9
                    'EPA EJScreen - Air Toxics Respiratory Hazard Index' = 'resp_hazard_ind', #10
                    'EPA EJScreen - Traffic Proximity and Volume' = 'traffic_proximity', #11
                    'EPA EJScreen - Ozone Seasonal Average of Daily Maximum 8-Hour Concentration (ppb)' = 'ozone_conc', #12
                    'EPA EJScreen - Annual Average PM2.5 Level in Air (ug/m3)' = 'pm_conc', #13
                    "Census' Community Resilience Index - Rate of Individuals with One or Two Risk Factors" = 'pct_1or2_risk_factors', #14
                    "Census' Community Resilience Index - Rate of Individuals with Three or More Risk Factors" = 'pct_3ormore_risk_factors', #15

                    '% High School Education' = 'fraction_high_school_edu', #16
                    'Median Income' = 'median_income', #17
                    'National Walkability Index' = 'walkability_index', #18
                    'Child Opportunity Index' = 'coi', #19
                    'Child Opportunity Index - Education Domain' = 'coi_education', #20
                    'Child Opportunity Index - Health and Environment Domain' = 'coi_health_env', #21
                    'Child Opportunity Index - Social and Economic Domain' = 'coi_social_econ', #22
                    
                    'Mental Health Professional Shortage Areas' = 'hpsa_mh', #23
                    'Primary Care Professional Shortage Areas' = 'hpsa_pc', #24
                    'Medically Underserved Areas' = 'mua' #25
                    )    
data_col = c('dep_index', 'adi', 'ice', 'fraction_poverty', 'fraction_assisted_income', 'fraction_no_health_ins', 'fraction_vacant_housing', 
             'lead_paint', 'diesel_pm', 'resp_hazard_ind', 'traffic_proximity', 'ozone_conc', 'pm_conc', 
             'pct_1or2_risk_factors', 'pct_3ormore_risk_factors', 
             'fraction_high_school_edu', 'median_income', 
             'walkability_index', 
             'coi', 'coi_education', 'coi_health_env', 'coi_social_econ', 
             'hpsa_mh', 'hpsa_pc', 'mua')

tm <- tm_shape(d.h, 
               name = 'Neiborhoods') +
  tm_polygons(col="neighborhood", 
              alpha = 0.2,
              legend.show = FALSE,
              id = "neighborhood",
              palette = "grey50",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[1:2], 
              title = names(legend_labels)[1:2],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[4:7], 
              title = names(legend_labels)[4:7],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[16:17], 
              title = names(legend_labels)[16:17],
              alpha = 0.5, 
              palette = 'viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[8:15], 
              title = names(legend_labels)[8:15],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[c(3, 18:22)], 
              title = names(legend_labels)[c(3, 18:22)],
              alpha = 0.5, 
              palette = 'viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col=data_col[23:25], 
              title = names(legend_labels)[23:25], 
              alpha = 0.2,
              legend.show = FALSE,
              id = "neighborhood",
              palette = c("green", "purple"),
              popup.vars = legend_labels) +
  tm_facets(as.layers = TRUE, 
            free.scales.fill = TRUE) 
  
tm %>% 
  leaflet.extras::addFullscreenControl()

```