---
title: "RISEUP Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill 
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(hrbrthemes)
library(tmap)
library(leaflet)
library(plotly)
```

```{css echo = FALSE}
li {
  line-height: 0.9;
}
```

Census Tract-Level Data in Hamilton County, Ohio
================================

Column {data-width=250}
-----------------------------------------------------------------------

<font size="3.5">

This map displays census tract-level data in Hamilton County.

Using the menu on the left-hand side of the map, you can toggle variables on/off.

Clicking on a census tract displays all variables for that census tract.

</font>

<font size="3">

Variables Include: 

  * [Community Material Deprivation Index](https://geomarker.io/dep_index)

  * [Neighborhood Atlas Area Deprivation Index](https://www.neighborhoodatlas.medicine.wisc.edu/)
      
  * [American Community Survey Sociodeomgraphic Variables](https://www.census.gov/programs-surveys/acs)
  
    + Fraction Assisted Income
    
    + Fraction High School Education
    
    + Median Income
    
    + Fraction No Health Insurance
    
    + Fraction Poverty
    
    + Fraction Vacant Housing
      
  * [National Walkability Index](https://www.epa.gov/smartgrowth/smart-location-mapping#walkability)
  
  * [Nancy Krieger's Index of Concentrated Extremes (ICE)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4815605/)
  
  * [EPA EJScreen](https://www.epa.gov/ejscreen)
  
      + Lead Paint Indicator
      
      + Concentration of Diesel Particulate Matter in Air (ug/m3)
      
      + Air Toxics Respiratory Hazard Index
      
      + Traffic Proximity and Volume
      
      + Ozone Seasonal Average of Daily Maximum 8-Hour Concentration (ppb)
      
      + Annual Average PM2.5 Level in Air (ug/m3)
      
  * [Child Opportunity Index](https://www.diversitydatakids.org/child-opportunity-index)
  
      + Overall
      
      + Education Domain
      
      + Health and Environment Domain
      
      + Social and Economic Domain
      
  * [Census' Community Resilience Index](Census' Community Resilience Index)
  
      + Rate of Individuals with One or Two Risk Factors
      
      + Rate of Individuals with Three or More Risk Factors
      
  * [Mental Health Professional Shortage Areas](https://data.hrsa.gov/topics/health-workforce/shortage-areas)
  
  * [Primary Care Professional Shortage Areas](https://data.hrsa.gov/topics/health-workforce/shortage-areas)
  
  * [Medically Underserved Areas](https://data.hrsa.gov/topics/health-workforce/shortage-areas)
  
</font>

<br>

<br>

<font size="2">

Map and figure created by CCHMC GRAPPH.

For questions, contact Cole.Brokamp@cchmc.org.

</font>


Column {data-width=750}
-----------------------------------------------------------------------

```{r map, fig.width = 13.5, fig.height = 10, fig.align='center'}

d.h <- readRDS("U:/Investigator Folders/DBE/Cole Brokamp/RISEUP/Census_tract_data_map/RISEUP-Census-Tract-Level-Data-Mapping/data/hamilton_data.rds")

tmap_mode('view')
tmap_options(max.categories = 81)


legend_labels <-  c('Community Material Deprivation Index' = 'dep_index', #1
                    'Neighborhood Atlas Area Deprivation Index' = 'adi', #2
                    'Index of Concentration at the Extremes' = 'ice', #3
                    '% Poverty' = 'fraction_poverty', #4
                    '% Assisted Income' = 'fraction_assisted_income', #5
                    '% No Health Insurance' = 'fraction_no_health_ins', #6
                    '% Vacant Housing' = 'fraction_vacant_housing', #7
                    'EPA EJScreen - Lead Paint Indicator' = 'lead_paint', #8
                    'EPA EJScreen - Concentration of Diesel Particulate Matter in Air (ug/m3)' = 'diesel_pm', #9
                    'EPA EJScreen - Air Toxics Respiratory Hazard Index' = 'resp_hazard_ind', #10
                    'EPA EJScreen - Traffic Proximity and Volume' = 'traffic_proximity', #11
                    'EPA EJScreen - Ozone Seasonal Average of Daily Maximum 8-Hour Concentration (ppb)' = 'ozone_conc', #12
                    'EPA EJScreen - Annual Average PM2.5 Level in Air (ug/m3)' = 'pm_conc', #13
                    "Census' Community Resilience Index - Rate of Individuals with One or Two Risk Factors" = 'pct_1or2_risk_factors', #14
                    "Census' Community Resilience Index - Rate of Individuals with Three or More Risk Factors" = 'pct_3ormore_risk_factors', #15

                    '% High School Education' = 'fraction_high_school_edu', #16
                    'Median Income' = 'median_income', #17
                    'National Walkability Index' = 'walkability_index', #18
                    'Child Opportunity Index' = 'coi', #19
                    'Child Opportunity Index - Education Domain' = 'coi_education', #20
                    'Child Opportunity Index - Health and Environment Domain' = 'coi_health_env', #21
                    'Child Opportunity Index - Social and Economic Domain' = 'coi_social_econ', #22
                    
                    'Mental Health Professional Shortage Areas' = 'hpsa_mh', #23
                    'Primary Care Professional Shortage Areas' = 'hpsa_pc', #24
                    'Medically Underserved Areas' = 'mua' #25
                    )    
data_col = c('dep_index', 'adi', 'ice', 'fraction_poverty', 'fraction_assisted_income', 'fraction_no_health_ins', 'fraction_vacant_housing', 
             'lead_paint', 'diesel_pm', 'resp_hazard_ind', 'traffic_proximity', 'ozone_conc', 'pm_conc', 
             'pct_1or2_risk_factors', 'pct_3ormore_risk_factors', 
             'fraction_high_school_edu', 'median_income', 
             'walkability_index', 
             'coi', 'coi_education', 'coi_health_env', 'coi_social_econ', 
             'hpsa_mh', 'hpsa_pc', 'mua')

tm <- tm_shape(d.h, 
               name = 'Neighborhoods') +
  tm_polygons(col="neighborhood", 
              alpha = 0.2,
              legend.show = FALSE,
              id = "neighborhood",
              palette = "grey50",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[1:2], 
              title = names(legend_labels)[1:2],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[4:7], 
              title = names(legend_labels)[4:7],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[16:18], 
              title = names(legend_labels)[16:18],
              alpha = 0.5, 
              palette = 'viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[8:15], 
              title = names(legend_labels)[8:15],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile", 
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col = data_col[c(3, 19:22)], 
              title = names(legend_labels)[c(3, 19:22)],
              alpha = 0.5, 
              palette = 'viridis', 
              style = "quantile",  
              midpoint=0,
              id = "id",
              popup.vars = legend_labels) +
  tm_shape(d.h) +
  tm_polygons(col=data_col[23:25], 
              title = names(legend_labels)[23:25], 
              alpha = 0.2,
              legend.show = FALSE,
              id = "neighborhood",
              palette = c("green", "purple"),
              popup.vars = legend_labels) +
  tm_facets(as.layers = TRUE, 
            free.scales.fill = TRUE) 
  
tm %>% 
  tmap_leaflet() %>%
  leaflet::hideGroup(names(legend_labels)[2:25]) %>% 
  leaflet.extras::addFullscreenControl()

```

Historical Air Quality Index (AQI) Data in Hamilton County, Ohio
================================

Column {data-width=250}
-----------------------------------------------------------------------

<font size="3">
The plot provides daily air quality index (AQI) from 01-01-2015 to 03-31-2022 for Hamilton county, Ohio. 

AQI has six categories as shown below:

<table>

AQI            Category
----------    -----------------------------------
0 to 50        <span style="background-color: lightgreen;">Good</span>
51 to 100      <span style="background-color: yellow;">Moderate</span>
101 to 150     <span style="background-color: orange;">Unhealthy for Sensitive Groups</span>
151 to 200     <span style="background-color: red;">Unhealthy</span>
201 to 300     <span style="color: purple;">Very Unhealthy</span>
301 to 500     <span style="color: maroon;">Hazardous</span>

The current air quality in Cincinnati area can be found on [AirNow](https://www.airnow.gov/?city=Cincinnati&state=OH&country=USA).

</table>

</font>


Column {data-width=750}
-----------------------------------------------------------------------

```{r, fig.width = 14, fig.height = 8, fig.align='center'}

aqi.hamilton <- readRDS("U:/Investigator Folders/DBE/Cole Brokamp/RISEUP/AQI/data/aqi_hamilton.rds")

p <- ggplot(aqi.hamilton, aes(x=Date, y=AQI)) +
  scale_x_date(limit=c(as.Date("2015-01-01"),as.Date("2022-03-31"))) +
  annotate("rect",
           xmin = as.Date("2015-01-01"), xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = 50,
           fill = "green",
           alpha = 0.2) + 
  annotate("rect",
           xmin = as.Date("2015-01-01"), xmax = as.Date("2022-03-31"),
           ymin = 51, ymax = 100,
           fill = "yellow",
           alpha = 0.2) + 
  annotate("rect",
           xmin = as.Date("2015-01-01"), xmax = as.Date("2022-03-31"),
           ymin = 101, ymax = 150,
           fill = "orange",
           alpha = 0.2) + 
  annotate("rect",
           xmin = as.Date("2015-01-01"), xmax = as.Date("2022-03-31"),
           ymin = 151, ymax = 200,
           fill = "red",
           alpha = 0.2) +
  geom_line( color="steelblue") + 
  xlab("Year") +
  ylab("Air Qualtiy Index") +
  theme_ipsum(axis_text_size = 12,
              axis_title_size = 14) 

ggplotly(p)

```





